config/routes.rb
ActressTwitter::Application.routes.draw do
  resources :twitter_accounts

end

app/models/twitter_account.rb
class TwitterAccount < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :set_twitter_account, only: [:show, :edit, :update, :destroy]

  # GET /twitter_accounts
  # GET /twitter_accounts.json
  def index
    @twitter_accounts = TwitterAccount.all
  end

  # GET /twitter_accounts/1
  # GET /twitter_accounts/1.json
  def show
  end

  # GET /twitter_accounts/new
  def new
    @twitter_account = TwitterAccount.new
  end

  # GET /twitter_accounts/1/edit
  def edit
  end

  # POST /twitter_accounts
  # POST /twitter_accounts.json
  def create
    @twitter_account = TwitterAccount.new(twitter_account_params)

    respond_to do |format|
      if @twitter_account.save
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @twitter_account }
      else
        format.html { render action: 'new' }
        format.json { render json: @twitter_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitter_accounts/1
  # PATCH/PUT /twitter_accounts/1.json
  def update
    respond_to do |format|
      if @twitter_account.update(twitter_account_params)
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @twitter_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_accounts/1
  # DELETE /twitter_accounts/1.json
  def destroy
    @twitter_account.destroy
    respond_to do |format|
      format.html { redirect_to twitter_accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_account
      @twitter_account = TwitterAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_account_params
      params.require(:twitter_account).permit(:actress, :twitter_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitter_account_helper.rb
module TwitterAccountHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActressTwitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/twitter_accounts/_form.html.erb
<%= form_for(@twitter_account) do |f| %>
  <% if @twitter_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_account.errors.count, "error") %> prohibited this twitter_account from being saved:</h2>

      <ul>
      <% @twitter_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actress %><br>
    <%= f.text_field :actress %>
  </div>
  <div class="field">
    <%= f.label :twitter_url %><br>
    <%= f.text_field :twitter_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_accounts/edit.html.erb
<h1>Editing twitter_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_account %> |
<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/index.html.erb
<h1>Actress Twitter Accounts</h1>
<h4>if an actress has a twitter account, click the link and check the account</h4>
<table>
	<thead>
		<tr>
			<th>Actress</th>
			<th>Twitter Url</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @twitter_accounts.each do |twitter_account| %>
		<tr>
			<td><%= twitter_account.actress %></td>
			<td> 
			<% if twitter_account.twitter_url %> 
				<a href="<%= 'https://twitter.com/'+twitter_account.twitter_url %>"><%= twitter_account.twitter_url %></a></td>
			<% end %>
			<td><%= link_to 'Show', twitter_account %></td>
			<td><%= link_to 'Edit', edit_twitter_account_path(twitter_account) %></td>
			<td><%= link_to 'Destroy', twitter_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Twitter account', new_twitter_account_path %>

app/views/twitter_accounts/new.html.erb
<h1>New twitter_account</h1>

<%= render 'form' %>

<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Actress:</strong>
  <%= @twitter_account.actress %>
</p>

<p>
  <strong>Twitter url:</strong>
  <%= @twitter_account.twitter_url %>
</p>

<%= link_to 'Edit', edit_twitter_account_path(@twitter_account) %> |
<%= link_to 'Back', twitter_accounts_path %>